name: lint and build
on:
  workflow_call:
    inputs:
      runnerOs:
        description: 'The runner OS'
        type: 'string'
        default: ubuntu-latest
      nodeVersion:
        type: 'string'
        default: '16'

jobs:
  #
  # Linting workflow to catch issues early and fail if conventions are not met
  #
  lint:
    name: Call Reusable Lint
    uses: colinbeales/actions-reusableworkflows/.github/workflows/lint.yml@main
    with: 
      nodeVersion: ${{ inputs.nodeVersion }}
      runnerOS: ${{ inputs.runnerOs }}

  #
  # Build and package application 
  #
  build:
    name: Build
 
    needs:
      - lint

    runs-on: ${{ inputs.runnerOS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Save Applicaton Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ inputs.runnerOs }}-${{ inputs.nodeVersion }}
          path: |
            .next/**
            public/**
            package.json
            next.config.js
